version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - /docker-c/redis.conf:/docker-c/redis.conf
    command: redis-server /docker-c/redis.conf

volumes:
  redis_data:
    driver: local